### PR TITLE
Use a mixin for LocalAuthenticator variant

### LINKED ISSUE #7: README Configuration
The Required Configuration section is a bit unclear.  I think you might want to swap out `c.LocalAuthenticator` for `c.JSONWebTokenLocalAuthenticator`.

### PR DESCRIPTION
**Pull request by yuvipanda**
- This uses the same pattern as in various OAuthenticators,
   for example https://github.com/jupyterhub/oauthenticator/blob/master/oauthenticator/github.py#L180
- Also cleanup README to point to more specific class names

Fixes #7

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thank you very much for this authenticator, @mogthesprog! I'm planning on using it for one of Berkeley's big classes (tens of thousands of students) soon, and am going to be making a series of PRs today / tomorrow!

**Comment by mogthesprog** [comment]
Awesome! :) 

I'll be on and off as i'm moving house, but i'll do my best to review/merge ASAP.

**Comment by yuvipanda** [comment]
gentlest of bumps :)

**Comment by mogthesprog** [comment]
oh snap, i'm sorry. I'll sort this right now.

**Review by mogthesprog — APPROVED** [review]

**Pull request merged**
